#!/bin/sh
# Install repo git hooks. Idempotent. The existing branch-guard pre-push (if
# any) is preserved by moving it to pre-push.local-previous, which the guard
# hook chains to — so both the branch guard and the security-sink guard run.
set -e

repo_root="$(git rev-parse --show-toplevel)"
hooks_dir="$repo_root/.git/hooks"
guard="$repo_root/scripts/security_sink_guard_prepush.sh"
target="$hooks_dir/pre-push"
chained="$hooks_dir/pre-push.local-previous"

if [ -f "$target" ] && ! grep -q "security_sink_guard_prepush.sh" "$target"; then
  mv "$target" "$chained"
fi

cat > "$target" <<EOF
#!/bin/sh
# Auto-generated by scripts/install_git_hooks.sh — edit the source, not this.
# guard gets </dev/null so push refs survive on stdin for the exec'd branch guard.
"$guard" "\$@" </dev/null || exit 1
[ -f "$chained" ] && exec "$chained" "\$@"
exit 0
EOF

chmod +x "$target" "$guard"
echo "Installed pre-push security-sink guard (chained to: ${chained##*/} if present)."
